import type { Metadata } from "next";
import "./globals.css";
import "@/public/css/font.css";
import Header from "./components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa">
      <body className="bg-[#de2d9c] p-5">
        <Header/>
        {children}
      </body>
    </html>
  );
}
